spring:
  application:
    name: paradaux-api

cloudflare:
  turnstile:
    secret: ${CLOUDFLARE_TURNSTILE_SECRET}

discord:
  webhook: ${DISCORD_WEBHOOK}

mybatis:
  type-aliases-package: io.paradaux.api.models
  mapper-locations: classpath:mappers/*.xml