spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

api:
  secret: ${API_SECRET}

maxmind:
  license-key: ${MAXMIND_LICENSE_KEY}
  user-id: ${MAXMIND_USER_ID}