spring:
  application:
    name: paradaux-api
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m

  data:
    redis:
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

cloudflare:
  turnstile:
    secret: ${CLOUDFLARE_TURNSTILE_SECRET}

discord:
  webhook: ${DISCORD_WEBHOOK}

mybatis:
  type-aliases-package: io.paradaux.api.models
  mapper-locations: classpath:mappers/*.xml
  type-handlers-package: io.paradaux.api.mappers.typehandlers

maxmind:
  base-url: https://download.maxmind.com/app/geoip_download